<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(ResonanceTfm)</TargetFramework>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\\Resonance.SignalR\Resonance.SignalR.csproj" />
    <ProjectReference Include="..\..\..\\Resonance\Resonance.csproj" />
  </ItemGroup>

</Project>
