<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(ResonanceWindowsTfm)</TargetFramework>
    <UseWPF>true</UseWPF>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.Debug" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Resonance\Resonance.csproj" />
    <ProjectReference Include="..\Resonance.Examples.Logging\Resonance.Examples.Logging.csproj" />
  </ItemGroup>

</Project>
