<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(ResonanceTfm)</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Resonance\Resonance.csproj" />
    <ProjectReference Include="..\Resonance.Messages\Resonance.Messages.csproj" />
    <ProjectReference Include="..\Resonance.Protobuf\Resonance.Protobuf.csproj" />
  </ItemGroup>

</Project>
