<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(ResonanceWindowsTfm)</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\\Resonance.SignalR\Resonance.SignalR.csproj" />
    <ProjectReference Include="..\..\..\\Resonance\Resonance.csproj" />
    <ProjectReference Include="..\..\Common\Resonance.Examples.Common\Resonance.Examples.Common.csproj" />
    <ProjectReference Include="..\Resonance.Examples.SignalR.Common\Resonance.Examples.SignalR.Common.csproj" />
  </ItemGroup>

</Project>
