<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(ResonanceWindowsTfm)</TargetFramework>
    <UseWPF>true</UseWPF>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\\Resonance\Resonance.csproj" />
  </ItemGroup>

</Project>
