<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(ResonanceTfm)</TargetFramework>
    <IsPackable>true</IsPackable>
    <Description>Protobuf Encoder &amp; Decoder for Resonance.

Resonance is a high-performance real-time C# communication library with built-in support for several different transcoding and delivery methods. This library provides an intuitive API for asynchronous communication between machines and devices by exposing a set of easy to use, pluggable components.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Resonance\Resonance.csproj" />
  </ItemGroup>

</Project>
